### ISSUE TITLE
Git repo missing source files

### ISSUE THREAD

**Issue by tburnett80** [qlik-oss/sse-r-plugin#13]
### Description

I cloned this repo to try and build the plugin but found its missing 
ServerSideExtension.cs
ServerSideExtensionGrpc.cs

from the project ServerSideExtension

What I suspect happened is someone added the files to their project and didn't add them to Git so when the push happened the updated solution file was pushed without the files. 

### Steps to Reproduce

1. Clone repo  https://github.com/qlik-oss/sse-r-plugin.git
2. Open solution in C sharp directory using Visual Studio

![capture](https://user-images.githubusercontent.com/4324080/31783093-aabb5386-b4c2-11e7-84a7-4a3ad47be2af.PNG)

**Comment by qlik-aoh** [comment]
Hi,

Those files are actually autogenerated and intentionally not committed to the git repo. The project should be setup so that the files are created when you build it, but if something has gone wrong you may need to run csharp/ServerSideExtension/generate_SSE_Stubs_from_proto.bat manually. (For more details about the setup, see @sam-sla's comment in https://github.com/qlik-oss/sse-r-plugin/issues/3 )

Let us know if you have any more trouble. You can also contact Qlik Support which usually has a quicker response time than we do.

Good luck, and hope you have fun using R in Qlik!
