### ISSUE TITLE
The Download ZIP not includes two files

### ISSUE THREAD

**Issue by marcosengineer** [qlik-oss/sse-r-plugin#3]
### Description
The Download ZIP not includes two files on csharp folder and whrn you try Build the solution on Visual Studio not works

[Description of the issue]

### Steps to Reproduce

1. [Step one]
Open the SLN project on Visual Studio

2. [Step two]
The Solution Explorer show the error about missing files

##### Expected behavior

[What you expected to happen]
The expected is no errors showed by Visual Studio to build the Solutions
##### Actual behavior

[What actually happened]
The Solution Explorer show the error about missing files and when you try buld the solutions not works swhow 41 errors and 27 warnings

##### Operating system where the SSE plugin is deployed
```
[X] Windows
[ ] Linux
```
##### Qlik Sense
```
[ ] Desktop
[X] Server
```
### Versions

* grpc-sse-r-plugin: 1.0.0
* Qlik Sense: June 2017
* Operating system: Windows Server 2012 R2
* [Other relevant versions]: Visual Studio 2015 Enterprise

**Comment by marcosengineer** [comment]
Hi Tobias

Can you include the files on ZIP

**Comment by qlik-aoh** [comment]
Hi Marcos,

It is unfortunate that you have problems, but can you please specify more details what errors you get?
I just tested to download the .zip and the solution built directly out-of-the box on my computer.

A wild guess is that there is a problem with the NuGets. Try this: open Solution Explorer in Visual Studio, right click on the solution and choose "Restore NuGet Packages". Then try building again.

Thanks,
Markus

**Comment by AnalyticsEarth** [comment]
I had similar issue, had to restore the NuGet packages.

Then you need to run the batch script in the server side extensions folder to build these two files which are missing using the proto file.

Note, if you upgrade the NuGet packages you might need to edit the path in the batch file.

Steven

Sent from my iPhone

On 29 Jun 2017, at 21:07, Markus Helgesson <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Marcos,

It is unfortunate that you have problems, but can you please specify more details what errors you get?
I just tested to download the .zip and the solution built directly out-of-the box on my computer.

A wild guess is that there is a problem with the NuGets. Try this: open Solution Explorer in Visual Studio, right click on the solution and choose "Restore NuGet Packages". Then try building again.

Thanks,
Markus

**Comment by JarkkoHanninen** [comment]
I had similar issues. Did not get it to work yet. Can you help me with this?

I did this:
1. Restored the NuGet packages (because of error message in Visual studio)
2. Run csharp\ServerSideExtension\generate_SSE_Stubs_from_proto file (because two files are missing: ServerSideExtension.cs and ServerSideExtensionGrpc.cs)
3. Tried to build the solution -> Still getting few error messages: "Metadata file .... csharp\ServerSideExtension\bin\Debug\ServerSideExtension.dll" could not be found.

In the future, is it possible that you provide also the prebuilt version of the solution (like in the technical preview phase) because this feels complicated to majority of people? Thanks!

/Jarkko

**Comment by kjartan-qlik** [comment]
I played around with this a bit to see if everything works as it should and while it compiled on first try for me I still have a few points:

 1. The missing files should be generated by a script and that's why they are not included. If all the NuGet packages are installed and of the correct version then the files should be generated when you press `build` in Visual Studio.
 2. In the Solution Explorer in Visual Studio, right click `SSEtoRserver` and select `Set as StartUp Project`
 3. Just to emphasize, you don't need to run the generating script manually since it's a build step in the solution file.
 4. If you update the packages to newer versions than what is specified in the packages.config files in the repository then there will be some broken paths and the solution will not compile.

Thanks for pointing out the issue with paths @AnalyticsEarth, we might have to find a better solution for that.

When I tested to update the packages and then trying to restore them to the original version I managed to make a whole mess of things and the simplest solution for me was to start from scratch by unzipping a new copy.

Hope this helps.

**Comment by sam-sla** [comment]
I just tried a fresh clone and it built fine out-of-the-box for me as well. Lets go step by step and see what is the expected output:

1. Open the solution and build it, it should restore the nuget packages, otherwise try a manual restore like Markus explained. **Output:** You should have a new directory `sse-r-plugin/csharp/packages/` with the Nuget packages inside (these are all new folders):
```
Google.Protobuf.3.2.0/
Grpc.1.2.2/
Grpc.Core.1.2.2/
Grpc.Tools.1.2.2/
Ix-Async.1.2.5/
NLog.4.4.9/
NLog.Config.4.4.9/
NLog.Schema.4.4.9/
RserveCLI2.1.0.22.0/
System.Collections.4.3.0/
System.Diagnostics.Debug.4.3.0/
System.Globalization.4.3.0/
System.Interactive.Async.3.1.1/
System.IO.4.3.0/
System.Linq.4.3.0/
System.Linq.Expressions.4.3.0/
System.ObjectModel.4.3.0/
System.Reflection.4.3.0/
System.Runtime.4.3.0/
System.Runtime.Extensions.4.3.0/
System.Text.Encoding.4.3.0/
System.Text.RegularExpressions.4.3.0/
```
2. Make sure everything builds by re-building the solution (after you have the nuget packages in place). Visual studio should execute the script that generates the missing files `ServerSideExtension.cs` and `ServerSideExtensionGrpc.cs`. **Output:** These two files will be placed in `sse-r-plugin/csharp/ServerSideExtension`. 
2.1: If the files are missing then the script must be failing for some reason, so you can execute it directly from windows command line. Open a command prompt and navigate to the folder `sse-r-plugin/csharp/ServerSideExtension` and just execute the script by typing its name on the command line `generate_SSE_Stubs_from_proto.bat`. **Output:**
![image](https://user-images.githubusercontent.com/19795751/27736402-5453d808-5da4-11e7-8228-e62125185ce1.png)

3. Now that you have all the nugets and the generated files `ServerSideExtension.cs, ServerSideExtensionGrpc.cs` the solution should build in visual studio. **Output:** in visual studio you  should see something like
```
1>------ Build started: Project: SSEtoRserve, Configuration: Debug Any CPU ------
1>  SSEtoRserve -> E:\GIT_alt-2\sse-r-plugin\csharp\SSEtoRserve\bin\Debug\SSEtoRserve.exe
========== Build: 1 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
```
With everything built, my folders look like:
_Folder:_ `csharp/ServerSideExtension/bin/Debug/` should have the contents:
```
Google.Protobuf.dll*
Google.Protobuf.xml
Grpc.Core.dll*
Grpc.Core.xml
grpc_csharp_ext.x64.dll*
grpc_csharp_ext.x86.dll*
libgrpc_csharp_ext.x64.dylib
libgrpc_csharp_ext.x64.so
libgrpc_csharp_ext.x86.dylib
libgrpc_csharp_ext.x86.so
ServerSideExtension.dll*
ServerSideExtension.pdb
System.Interactive.Async.dll*
System.Interactive.Async.xml
```
_Folder:_ `csharp/SSEtoRserve/bin/Debug/` should have the contents:
```
Google.Protobuf.dll*
Google.Protobuf.xml
Grpc.Core.dll*
Grpc.Core.xml
grpc_csharp_ext.x64.dll*
grpc_csharp_ext.x86.dll*
libgrpc_csharp_ext.x64.dylib
libgrpc_csharp_ext.x64.so
libgrpc_csharp_ext.x86.dylib
libgrpc_csharp_ext.x86.so
NLog.config
NLog.dll*
NLog.xml
RserveCLI2.dll*
RserveCLI2.xml
ServerSideExtension.dll*
ServerSideExtension.pdb
SSEtoRserve.exe*
SSEtoRserve.exe.config
SSEtoRserve.pdb
System.Interactive.Async.dll*
System.Interactive.Async.xml
```
Hope this helps to troubleshoot what is going wrong so you can go ahead and start using the plugin :)

**Comment by marcosengineer** [comment]
Hi For all

The issue was solved and i can use the extension, Thanks for all

**Comment by Steeefan** [comment]
I had the same issue and nothing suggested here seemed to work. Turns out having a folder somewhere down the folder tree that contains a space breaks it.

**Comment by stephanegrimaud** [comment]
Well, my problem persists even if all the required steps are ok. The NuGet packages are up-to-date. The missing files have been generated by the batch file.

I don't know what to do to go further.

Here are the error messages I get :

![2017-11-08_14h50_42](https://user-images.githubusercontent.com/33480867/32552510-7ad368d4-c494-11e7-8579-ee4b9d0e2ae1.png)

Thanks for your help.

Stéphane

**Comment by qlik-aoh** [comment]
@stephanegrimaud There is a problem with whitespaces in the path. I have a fix coming up, but we'll handle it in your reported issue, #16.
