### ISSUE TITLE
QlikSense unable to use R functions (appear as text)

### ISSUE THREAD

**Issue by mssqlsage** [qlik-oss/sse-r-plugin#37]
### Description

Hi guys,

   Hoping you can help me out getting the SSE-R-Plugin up and running.  Here's the issue:

![image](https://user-images.githubusercontent.com/39274715/40011927-3a47499a-5777-11e8-9949-c33d4cc2f0cb.png)

In the sheet R_BasicExample, the R functions are appearing as text.  It looks like Sense isn't able to connect to R - when I edit them, they just tell me the expression is invalid.

This is on QlikSense Feb 2018, Patch 1.

I run into similar problems when creating my own sheets.

I have the R analytic connection enabled:

![image](https://user-images.githubusercontent.com/39274715/40012044-8630978a-5777-11e8-8e2e-2d2516eb32a1.png)

RServe is running:

![image](https://user-images.githubusercontent.com/39274715/40012086-9c5d8d4c-5777-11e8-97ce-17d6f8991d53.png)

The plugin is running, and appears connected to R:

![image](https://user-images.githubusercontent.com/39274715/40012157-ca2bcc84-5777-11e8-960b-4ff6f96da2ca.png)

Note that at the bottom, there are messages about client calls when I restart the QlikSense Engine Service

The JSON Functions are also defined locally, and can be seen loading in the plugin initialization.
No certs are defined; I've tried connecting directly via the central node or using the full sense URL, same result.

Any idea what I could be missing ?

Thanks for your help !

Jeff

### Environment
Windows Server 2016
x64

##### Operating system where the SSE plugin is deployed
```
[X ] Windows
[ ] Linux
```
##### Qlik Sense
```
[ ] Desktop
[X ] Server
```
### Versions
QlikSense Feb 2018, Patch 1.

* sse-r-plugin: Most recent
* Qlik Sense: Feb 2018 Patch 1
* Operating system: Server 2016
* [Other relevant versions]

**Comment by tobiaslindulf** [comment]
-Are you running the SSE plugin in the central Sense node?
-In "SSEtoRserve.exe.config" file, have you set the setting "grpcHost" to "0.0.0.0" instead of localhost?
-Can you check the firewall settings on the machine, just to see that you allow traffic on 50051?

Can you make sure that the name of the plugin in QMC is named exactly "R" , just so you accidently have not added extra white spaces in the name.

I cannot figure of something else actually, should work after those steps. An extra restart of the engine service is also good to do.

**Comment by mssqlsage** [comment]
Tobias,  

  Thanks for replying.


-In "SSEtoRserve.exe.config" file, have you set the setting "grpcHost" to "0.0.0.0" instead of localhost?
Yes:
![image](https://user-images.githubusercontent.com/39274715/40062133-8272c5b2-5828-11e8-9f81-6f07dc0441f8.png)

-Can you check the firewall settings on the machine, just to see that you allow traffic on 50051?
Everything is running locally and windows firewall is off, but I'll see if there's anything else that could be blocking.

I also get this error when attempting to use the data load editor:
![image](https://user-images.githubusercontent.com/39274715/40062359-0bdc2f3c-5829-11e8-837c-5b3da7985cef.png)

-Can you make sure that the name of the plugin in QMC is named exactly "R" 
  Yes, double checked.  Just R without any other characters.

**Comment by tobiaslindulf** [comment]
This is strange. I can think of three more things to check.
1. In the  "SSEtoRserve.exe.config" file, is allowScript set to True (seems like it from the cmd logs)?

2. Can you try with another browser, just in case. What happens if you make selections in the list boxes?

3. Have you modified any rules in the QMC? 

Maybe the next thing is to send the engine logs (SSE logs and engine system logs) to see what it say.

**Comment by mssqlsage** [comment]
Hi Tobias,

 Thanks again for responding.

 1.  Yes, set to True.
 2.  I usually use Chrome, but checked with IE - same result
 3.  We do have many custom rules in QMC - is it possible there's something that would be affecting this ?  I couldn't think of anything other than analytic connection rules, which seem ok to me.

I also checked with our networking/sysadmin to make sure firewall and antivirus issues were not present, and it doesn't appear they are.

I installed this on a separate staging server and got the same results.  All logs (including the engine logs) indicate the plugin is successfully connected to via Qlik.  

One other thing - I am using the provided binaries; should I try to build the solution locally ?  I hadn't really considered this since the plugin appears to be running.

Jeff

**Comment by tobiaslindulf** [comment]
This is really really strange. All seems good then and it still does not show any data from the plugin.
What happens when you make some selections and so on, same thing I guess.
No, no need to compile the plugin yourself, no difference.
One more thing you can try is to actually try Sense Desktop and connect to the same plugin machine.

**Comment by mssqlsage** [comment]
Making selections in the app does change the data in the charts, but doesn't impact the R calculations (they still just have the text of the function call rather than results).

One odd thing I noticed is this:

![image](https://user-images.githubusercontent.com/39274715/40728304-d075bf50-63f7-11e8-8a0b-4b8932f9ea0b.png)

That happens when I restart the engine, but the port seems to be random/dynamic and mentions IPV6; we have a pretty standard network configuration.  Is this abnormal for the plugin ?

I will give desktop a try to see if results are the same.

Thanks,
Jeff

**Comment by mssqlsage** [comment]
I realized I never responded with the eventual solution -  I changed the Host under QMC --> Analytic connection to the IPV4 IP address.  For some reason, this solved the intermittent connectivity problem.
