### ISSUE TITLE
Unable to import R extensions

### ISSUE THREAD

**Issue by BdeKort** [qlik-oss/sse-r-plugin#49]
### Description

I get an error message in Qlik Sense Enterprise version September 2018 that "the zip file doesn't contain any valid extensions".

### Steps to Reproduce

1. Download sse-r-plugin-1.2.1-qlik-oss.zip
2. Open the extension section in the QMC
3. Import extension sse-r-plugin-1.2.1-qlik-oss.zip

##### Expected behavior

Extension should be imported succesfully and added to the list of extensions.

##### Actual behavior

Error message apears: "the zip file doesn't contain any valid extensions".

##### Operating system where the SSE plugin is deployed
```
[x ] Windows
[ ] Linux
```
##### Qlik Sense
```
[ ] Desktop
[x ] Server
```
### Versions

* sse-r-plugin:1.2.1
* Qlik Sense: September 2018 patch 1
* Operating system: Windows server 2016
![unable to import r extensions](https://user-images.githubusercontent.com/31821274/48076559-bbd72680-e1e5-11e8-9d0b-40279bd81880.PNG)

**Comment by tobiaslindulf** [comment]
Hi, the zip file you mention is NOT a client extension, it contains the server that is running the actual R calculations.
Download the following pre-built executables, unzip it to where R is deployed:
https://github.com/qlik-oss/sse-r-plugin/releases/download/v1.2.1/sse-r-plugin-1.2.1-qlik-oss.zip 
Look at the guides at the following links: https://github.com/qlik-oss/server-side-extension/blob/master/docs/configuration.md 
Read the getting started guide (but skip the step 2 since it is already built in the zip file mentioned above): https://github.com/qlik-oss/sse-r-plugin/blob/master/GetStarted.md 

I hope this helps.

**Comment by BdeKort** [comment]
Hi Tobias,

Thanks for your assistance and for clearing up the misunderstanding ;-).

Regards,

Bram
